#!/bin/bash
# Deploy to Apps Script and output test URLs for all tenants

set -e

echo "🚀 Deploying to Google Apps Script..."
echo ""

# Push latest code
echo "📤 Pushing code to Apps Script..."
npx @google/clasp push --force

echo ""
echo "✅ Code pushed successfully!"
echo ""

# Create new deployment
echo "📦 Creating new deployment..."
DEPLOY_OUTPUT=$(npx @google/clasp deploy --description "Deployment $(date '+%Y-%m-%d %H:%M:%S')" 2>&1)
echo "$DEPLOY_OUTPUT"

echo ""
echo "🔍 Getting deployment information..."
DEPLOYMENTS=$(npx @google/clasp deployments 2>&1)
echo "$DEPLOYMENTS"
echo ""

# Try to extract URL from deployments output
WEBAPP_URL=$(echo "$DEPLOYMENTS" | grep -oP 'https://script\.google\.com/macros/s/[^\s]+' | head -1)

# If no URL found, provide instructions to get it
if [ -z "$WEBAPP_URL" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ DEPLOYMENT SUCCESSFUL!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "⚠️  Please get your Web App URL manually:"
    echo ""
    echo "1. Open: https://script.google.com/home/projects/1KttRXT0Sq2663irNS0FlUi3mMkHL9QisErtY4pAqwtqPKH2ZuS7y_Upe/edit"
    echo "2. Click 'Deploy' → 'Manage deployments'"
    echo "3. Find deployment @21 (most recent)"
    echo "4. Copy the 'Web app' URL"
    echo ""
    echo "Then use this URL format for testing:"
    echo ""
    echo "Root Admin:     {URL}?page=admin&tenant=root"
    echo "Root Analytics: {URL}?page=report&tenant=root"
    echo "ABC Admin:      {URL}?page=admin&tenant=abc"
    echo "ABC Analytics:  {URL}?page=report&tenant=abc"
    echo ""
    exit 0
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 DEPLOYMENT SUCCESSFUL!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 BASE URL:"
echo "$WEBAPP_URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏢 ROOT TENANT (Zeventbook)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Admin Page:"
echo "${WEBAPP_URL}?page=admin&tenant=root"
echo ""
echo "📊 Shared Analytics (NEW!):"
echo "${WEBAPP_URL}?page=report&tenant=root"
echo ""
echo "Public Page:"
echo "${WEBAPP_URL}?page=public&tenant=root"
echo ""
echo "Display Page (TV):"
echo "${WEBAPP_URL}?page=display&tenant=root"
echo ""
echo "Poster Page (Print):"
echo "${WEBAPP_URL}?page=poster&tenant=root"
echo ""
echo "Test Dashboard:"
echo "${WEBAPP_URL}?page=test&tenant=root"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 ABC TENANT (American Bocce Co.)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Admin Page:"
echo "${WEBAPP_URL}?page=admin&tenant=abc"
echo ""
echo "📊 Shared Analytics (NEW!):"
echo "${WEBAPP_URL}?page=report&tenant=abc"
echo ""
echo "Public Page:"
echo "${WEBAPP_URL}?page=public&tenant=abc"
echo ""
echo "Display Page (TV):"
echo "${WEBAPP_URL}?page=display&tenant=abc"
echo ""
echo "Poster Page (Print):"
echo "${WEBAPP_URL}?page=poster&tenant=abc"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏆 CBC TENANT (Chicago Bocce Club)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Admin Page:"
echo "${WEBAPP_URL}?page=admin&tenant=cbc"
echo ""
echo "📊 Shared Analytics (NEW!):"
echo "${WEBAPP_URL}?page=report&tenant=cbc"
echo ""
echo "Public Page:"
echo "${WEBAPP_URL}?page=public&tenant=cbc"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚽ CBL TENANT (Chicago Bocce League)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Admin Page:"
echo "${WEBAPP_URL}?page=admin&tenant=cbl"
echo ""
echo "📊 Shared Analytics (NEW!):"
echo "${WEBAPP_URL}?page=report&tenant=cbl"
echo ""
echo "Public Page:"
echo "${WEBAPP_URL}?page=public&tenant=cbl"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 API & DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "API Documentation:"
echo "${WEBAPP_URL}?page=api"
echo ""
echo "System Status:"
echo "${WEBAPP_URL}?page=status"
echo ""
echo "Diagnostics:"
echo "${WEBAPP_URL}?page=diagnostics&tenant=root"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 TESTING TIPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start with Admin page to create test events"
echo "2. Check the Shared Analytics page (NEW feature!)"
echo "3. Test mobile responsiveness (F12 → Toggle device)"
echo "4. Verify all TRIANGLE pages (Admin → Poster → Display → Public)"
echo ""
echo "📝 Save these URLs for easy testing!"
echo ""
