# DEPRECATED WORKFLOW (ARCHIVED)
# This workflow is kept for historical reference only.
# Do NOT re-enable without updating it to the current CI/CD architecture.

name: OLD – Stage 2 - Sequential Progressive Testing

on:
  # Auto-trigger when Stage 1 completes successfully
  # MVP SRE Policy: Only run full Playwright on main/release, not feature branches
  workflow_run:
    workflows: ["Stage 1 - Build & Deploy"]
    types: [completed]
    branches:
      - main
      - 'release/**'
      - 'release/*'

  # Manual trigger for "I want full regression" runs
  workflow_dispatch:
    inputs:
      deployment_url:
        description: 'Deployment URL to test (leave empty to use Stage 1 output)'
        required: false
        type: string
        default: ''
      use_production:
        description: '⚠️ DANGER: Run minimal smoke tests against PRODUCTION (www.eventangle.com). Only workflow_dispatch. Read-only tests ONLY. Use with extreme caution!'
        required: false
        type: boolean
        default: false

# Prevent duplicate runs: only one Stage 2 at a time per branch
# Note: cancel-in-progress: false ensures runs queue instead of cancelling each other
# This provides deterministic test results - cancelled runs give no useful feedback
concurrency:
  group: stage2-${{ github.event.workflow_run.head_branch || github.ref }}
  cancel-in-progress: false

jobs:
  # NOTE: This is an archived/deprecated workflow.
  # The full implementation has been removed for brevity.
  # See the active stage2.yml workflow for the current implementation.

  placeholder:
    name: 📦 Archived Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "=============================================="
          echo "⚠️  DEPRECATED WORKFLOW"
          echo "=============================================="
          echo ""
          echo "This workflow has been archived."
          echo "Please use the active stage2.yml workflow instead."
          echo ""
          echo "=============================================="
          exit 1
